version: '2'
services:
  dnsmasq:
    image: jpillora/dnsmasq
    container_name: dnsmasq
    volumes:
      - ../../conf/dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf
      - ../../conf/dnsmasq/resolv.dnsmasq:/etc/resolv.dnsmasq
      - ../../conf/dnsmasq/hosts.dnsmasq:/etc/hosts.dnsmasq
    ports:
      - 5380:8080
      - 53:53/tcp 
      - 53:53/udp
    environment:
      - HTTP_USER=admin
      - HTTP_PASS=admin