version: '2'
services:
  xxljob:
    image: xuxueli/xxl-job-admin:2.2.0
    container_name: xxljob
    volumes:
      - ../../data/xxljob/log/applogs:/data/applogs
    ports:
      - 9999:8080
    environment:
      TZ: Asia/Shanghai
      PARAMS: "--spring.datasource.url=jdbc:mysql://192.168.1.100:3306/xxl_job?useSSL=false&useUnicode=true&characterEncoding=utf-8&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai --spring.datasource.username=root --spring.datasource.password=Flzx3000c"

