version: '2'
services:
  elasticsearch:
    image: elasticsearch:6.6.0
    container_name: elasticsearch
    volumes:
      - ../../data/elasticsearch/data/:/usr/share/elasticsearch/data
      - ../../conf/elasticsearch/plugins:/usr/share/elasticsearch/plugins
      - ../../conf/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ../../conf/elasticsearch/etc/security/limits.conf:/etc/security/limits.conf
    environment:  
      - TZ=Asia/Shanghai
      - ES_CLUSTERNAME=elasticsearch
    command: elasticsearch
    ports:  
      - 9200:9200
      - 9300:9300





