version: '2'
services:
  zentao:
      image: idoop/zentao
      container_name: zentao
      volumes:
        - ../../data/zbox/:/opt/zbox/
      ports:
        - 80:80
        - 3306:3306
      environment:
        - ADMINER_USER=root
        - ADMINER_PASSWD=root
        - BIND_ADDRESS=false