version: '2'
services:
  redis1:
    image: redis:5.0.6
    container_name: redis1
#    volumes:
#      - ../../data/redis1/data:/data
    ports:
      - "6370:6370"
      - "16370:16370"
    command: 
      - "--appendonly no"
      - "--port 6370"
      - "--cluster-enabled yes"
      # - "redis-cli --cluster create 192.168.31.204:6370 192.168.31.204:6371 192.168.31.204:6372"
    environment:
      - TZ=Asia/Shanghai
  redis2:
    image: redis:5.0.6
    container_name: redis2
#    volumes:
#      - ../../data/redis2/data:/data
    ports:
      - "6371:6371"
      - "16371:16371"
    command: 
      - "--appendonly no"
      - "--port 6371"
      - "--cluster-enabled yes"
    environment:
      - TZ=Asia/Shanghai
  redis3:
    image: redis:5.0.6
    container_name: redis3
#    volumes:
#      - ../../data/redis3/data:/data
    ports:
      - "6372:6372"
      - "16372:16372"
    command: 
      - "--appendonly no"
      - "--port 6372"
      - "--cluster-enabled yes"
    environment:
      - TZ=Asia/Shanghai
