version: '2'
services:
  jenkins:
    image: jenkins/jenkins:2.198 
    container_name: jenkins
    volumes:
      - ../../data/jenkins:/var/jenkins_home
    ports:
      - "8090:8080"
      - "50000:50000"
    environment:
      - TZ=Asia/Shanghai
