version: '2'
services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ../../conf/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ../../conf/nginx/conf/conf.d:/etc/nginx/conf.d
      - ../../data/certbot/letsencrypt:/certbot/letsencrypt
      - ../../html:/html:ro
    ports:
      - 80:80
      - 443:443
    environment:
      - TZ=Asia/Shanghai